name: childrights
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  flutter_floating_bottom_bar: ^1.2.0
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.2.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  http: ^1.1.0
  crypto: ^3.0.3
  convert: ^3.1.1
  toast: ^0.3.0
  flutter_toastr: ^1.0.3
  fluttertoast: ^8.2.2
  cloud_firestore: ^4.9.3
  confetti: ^0.7.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_fortune_wheel: ^1.3.0
  cached_network_image: ^3.3.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  assets_audio_player: ^3.1.1
  audioplayers: ^5.2.0
  just_audio: ^0.9.35
  audio_service: ^0.18.12
  provider: ^6.0.5
  chat_bubbles: ^1.5.0
  velocity_x: ^4.1.2
  flutter_dotenv: ^5.1.0
  chat_gpt_sdk: ^2.2.5
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
         - assets/
         - assets/sounds/
   

  fonts:
   - family: Cera Pro
     fonts:
          - asset: assets/fonts/Cera-Pro-Bold.otf
          - asset: assets/fonts/Cera-Pro-Medium.otf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
